language: node_js

node_js:
  - '8'

script:
  - npm run coverage

before_deploy:
  - openssl aes-256-cbc -K $encrypted_e7e7a4b212eb_key -iv $encrypted_e7e7a4b212eb_iv -in travis_ci_deploy_rsa.enc -out travis_ci_deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 travis_ci_deploy_rsa
  - ssh-add travis_ci_deploy_rsa

deploy:
  provider: script
  script:
    - bash ./deploy.sh
  on:
    branch: master
